# Bind prefix to C + /
unbind C-b
set-option -g prefix C-_
bind-key C-_ send-prefix

# Bind v and h to split screen
bind v split-window -h
bind h split-window -v

unbind '"'
unbind %

set -g allow-passthrough on

# Enable mouse
set -g mouse on

# Tmux plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jabirali/tmux-minimono'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
run '~/.tmux/plugins/tpm/tpm'

# Yank with Y in visual mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

set -s copy-command 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Change panels with hjkl
bind k selectp -U # switch to panel Up
bind j selectp -D # switch to panel Down 
bind h selectp -L # switch to panel Left
bind l selectp -R # switch to panel Right

bind N command-prompt -p "session name:" "new-session -s '%%'"

# Show datetime in status bar
set -g status-right "%H:%M %d-%m-%Y"

bind r source-file ~/.tmux.conf \; display-message "config reloaded"
bind-key C-n command-prompt -p "New session name:" "new-session -s '%%'"
